feat(APPT-STQA-74): Added the appointment booking web page (layout)
cgerard321/STQA-pet-clinic-F2020 pull request #40
Opened 2020-11-09 03:06 UTC by Colorin09

Here is the layout for the book appointment webpage. the database data is not done yet.

2020-11-09 03:13 UTC, sylveon commented
Lots of clutter going on here, could you fix that?
![image](https://user-images.githubusercontent.com/6440374/98496445-a7ccc200-220f-11eb-99c9-88f1a148a7b6.png)

2020-11-10 00:17 UTC, sylveon commented on src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
> +    private static final String appointForm = "appointments/appointments";
Use shout case for constants

2020-11-10 00:17 UTC, sylveon commented on src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
> +    public String initCreationForm(Map<String, Object> vetInfo) {
Unused parameter, remove it

2020-11-10 00:18 UTC, sylveon commented on src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
>      @GetMapping(value = "/appointments")
```suggestion
    @GetMapping(value = "/appointments/create")
```

2020-11-10 00:20 UTC, sylveon commented on src/main/webapp/WEB-INF/jsp/appointment.jsp
> +<%@ page session="false" trimDirectiveWhitespaces="true" %>
Rename this to `createAppointment.jsp`

2020-11-10 00:20 UTC, sylveon commented on src/main/webapp/WEB-INF/jsp/appointments/appointments.jsp
>  <%@ page session="false" trimDirectiveWhitespaces="true" %>
Rename this to createAppointment.jsp

2020-11-10 00:21 UTC, sylveon requested changes
Looks pretty decent, few minor comments though

2020-11-10 00:48 UTC, sylveon submitted a review, later dismissed

2020-11-10 01:29 UTC, GSwizzy submitted a review, later dismissed

2020-11-10 01:43 UTC, sylveon approved these changes

2020-11-10 01:45 UTC, GSwizzy approved these changes

2020-11-10 01:45 UTC, merged